steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/canvas-modem-457011-p6/gcpdevops", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/canvas-modem-457011-p6/gcpdevops"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/canvas-modem-457011-p6/gcpdevops
      - --location=us-central1-c
      - --cluster=gcp-devps-project
      - --namespace=gcp-devops-prod
